export declare const COLS = 10;
export declare const ROWS = 20;
export declare const BLOCK_SIZE = 30;
export declare const NEXT_COLS = 4;
export declare const NEXT_ROWS = 4;
export declare const SHAPES: number[][][];
export declare const COLORS: string[];
export declare const KEY: {
    LEFT: string;
    RIGHT: string;
    DOWN: string;
    UP: string;
    SPACE: string;
    P: string;
};
export declare const POINTS: {
    SINGLE: number;
    DOUBLE: number;
    TRIPLE: number;
    TETRIS: number;
    SOFT_DROP: number;
    HARD_DROP: number;
};
export declare const LEVEL: {
    0: number;
    1: number;
    2: number;
    3: number;
    4: number;
    5: number;
    6: number;
    7: number;
    8: number;
    9: number;
    10: number;
    11: number;
    12: number;
    13: number;
    14: number;
    15: number;
    16: number;
    17: number;
    18: number;
    19: number;
    20: number;
};
